from .nmap_tab import NmapTab
from .sqlmap_tab import SqlmapTab
from .nuclei_tab import NucleiTab
from .nikto_tab import NiktoTab
from .gobuster_tab import GobusterTab
from .dirsearch_tab import DirsearchTab
from .commix_tab import CommixTab
from .netcat_tab import NetcatTab
from .metasploit_tab import MetasploitTab
