services:

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    networks:
      - pentest-net

  pentester:
    build: .
    container_name: pentester
    working_dir: /work
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    volumes:
      - ./results:/results
      - ./wordlists:/wordlists

    networks:
      - pentest-net

networks:
  pentest-net:
    driver: bridge
