services:

  #  SERVIÇO DVWA
  
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"
    networks:
      - pentest-net

 
  #  SERVIÇO PENTESTER 
  
  pentester:
    build: .
    container_name: pentester
    working_dir: /work
    profiles: ["tools"]
    volumes:
      - ./results:/results
      - ./wordlists:/wordlists


    networks:
      - pentest-net

  #  SERVIÇO METASPLOIT
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    profiles: ["tools"]
    volumes:
      - ./results:/results
    networks:
      - pentest-net

networks:
  pentest-net:
    driver: bridge

volumes:
  ollama_data:
