services:

  # ===================================================
  #  SERVIÇO BASE (TODAS AS FERRAMENTAS)
  # ===================================================

  # ===================================================
  #  SERVIÇO DVWA (Damn Vulnerable Web Application)
  # =================================================== 
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8081:80"

  # ===================================================
  #  SERVIÇO OLLAMA (Modelo de Linguagem)
  # =================================================== 
  ollama:
   image: ollama/ollama
   container_name: ollama
   ports:
    - "11434:11434"

   volumes:
    - ollama_data:/root/.ollama
   

  pentester:
    build: .
    container_name: pentester
    working_dir: /work
    profiles: ["tools"]
   #entrypoint: ["bash"]
    volumes:
      - ./results:/results
      - ./wordlists:/wordlists
      - ./nuclei-templates:/opt/nuclei-templates

  # ===================================================
  #  SERVIÇO METASPLOIT (Oficial da Rapid7 - Leve e Otimizado)
  # =================================================== 
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    profiles: ["tools"]
    volumes:
      - ./results:/results
volumes:
  ollama_data:
